// <auto-generated />
namespace PokeTrack.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class draft1finished : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(draft1finished));
        
        string IMigrationMetadata.Id
        {
            get { return "202010092029523_draft1finished"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
